### ISSUE TITLE
Why two mixins?

### ISSUE THREAD

**Issue by tamagokun** [rattrayalex/fluxbone#1]
First off, taking an old Chaplin (Backbone with some other stuff) application and making the move to React probably wouldn't have been possible without discovering how you are integrating React with Backbone in such a simple way.

One thing that I don't understand is why you have a `ModelMixin` and a `CollectionMixin` for the same exact functionality? I've condensed it down to one mixin so you can just call `fluxbone.Mixin('foo')`.

**Comment by rattrayalex** [comment]
Haha good question. I think there used to be a reason but it was refactored
out. I'll take a look at fixing that!

Thanks!
