### ISSUE TITLE
Misspellings in examples

### ISSUE THREAD

**Issue by ericmasiello** [rattrayalex/fluxbone#2]
Author = Backbone.Model.exented({})
Book = Backbone.Model.exented({})

Should be .extend()

**Comment by rattrayalex** [comment]
Whoops! Thanks so much for this - I'll fix today or tomorrow.

**Comment by ericmasiello** [comment]
Thanks! Would you also mind extending your sample code to the point where you actually render it onto the DOM using React.render()?

**Comment by rattrayalex** [comment]
Yeah great idea!
I updated the docs - let me know what you think.

**Comment by rattrayalex** [comment]
... ended up updating rather significantly, including adding an `example` dir with full runnable example

**Comment by ericmasiello** [comment]
Great! Thanks so much. I'll check it out.
