### ISSUE TITLE
CollectionMixin vs ModelMixin vs. Mixin

### ISSUE THREAD

**Issue by ericmasiello** [rattrayalex/fluxbone#3]
It looks like in 1.1 you added FluxBone.Mixin. Can you explain the difference between that and CollectionMixin or ModelMixin?

**Comment by rattrayalex** [comment]
Check the source (`index.coffee`) - they're all the same thing. ModelMixin and CollectionMixin were different at some point before I pushed to npm I think, shouldn't have had different names even at that point.

**Comment by rattrayalex** [comment]
I'll leave this issue open so others can see it.
