### ISSUE TITLE
ratio of dispatchers to stores

### ISSUE THREAD

**Issue by ORESoftware** [rattrayalex/fluxbone#4]
It seems to me after reading about React/Flux w/ Backbone for a few hours, that there should be one dispatcher for every store. That is, a 1:1 ratio. So for each Backbone.Collection instance or Backbone.Model instance there should be a dispatcher. Is this correct/advisable? If this is the recommended pattern, could you make this a little more clear in your write up? thanks for this project and if what I am requested is already made clear and I missed it, please disregard!

**Comment by rattrayalex** [comment]
I think one dispatcher per application is fine... not sure why you would want more than one.
