### ISSUE TITLE
Question - how to "Fluxify" AJAX responses using a library like Backbone

### ISSUE THREAD

**Issue by ORESoftware** [rattrayalex/fluxbone#5]
@rattrayalex if you don't mind, could help answer this question?

http://programmers.stackexchange.com/questions/296949/flux-architecture-w-backone-how-to-use-action-creators-for-all-http-responses

maybe put the answer here as well, thank you!

**Comment by ORESoftware** [comment]
perhaps you agree with this?
http://blog.rile.yt/react-backbone-flux-async-web-apis

**Comment by rattrayalex** [comment]
There are definitely different ways to do it. If you want to go with the FluxBone pattern I put forward (which I do not currently use), I would recommend simply calling `this.save()` in your flux handlers. You can then listen to the `'request'` `'sync'` and `'error'` events in your views and display states accordingly.

**Comment by rattrayalex** [comment]
does that make sense?

**Comment by ORESoftware** [comment]
let me think about it
